{% set version = "0.5.0" %}

package:
  name: jsonarango
  version: {{ version }}

source:
  url: https://bitbucket.org/gems4/jsonarango/get/v{{ version }}.tar.gz
  sha256: e0e3c5c65a21301515fa4459311801fbd0cfaa790e4e2fc9949c29a7d1b78809

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - make
  host:
    - curl
    - velocypack

test:
  commands:
    - test -d ${PREFIX}/include/jsonarango  # [unix and osx]
    - test -f ${PREFIX}/include/jsonarango/arangoquery.h  # [unix and osx]
    - if exist %LIBRARY_PREFIX%\include\jsonarango\arangoquery.h (exit 0) else (exit 1)  # [win]

about:
  home: https://bitbucket.org/gems4/jsonarango
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: A lightweight ArangoDB client C++ library, providing CRUD and query operations
  doc_url: https://bitbucket.org/gems4/jsonarango
  dev_url: https://bitbucket.org/gems4/jsonarango

extra:
  recipe-maintainers:
    - gdmiron
    - sdmytrievs
