{% set version = "0.3.0" %}

package:
  name: jsonarango
  version: {{ version }}

source:
  url: https://bitbucket.org/gems4/jsonarango/get/v{{ version }}.tar.gz
  sha256: 2e067e960d948a0d826f115f0e76933bf98f1842e3856ac24e4c88ab49e2e5f8

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - make  # [unix and osx]
  host:
    - curl
    - velocypack

test:
  commands:
    - test -d ${PREFIX}/include/jsonarango  # [unix and osx]
    - test -f ${PREFIX}/include/jsonarango/arangoquery.h  # [unix and osx]
    - if exist %LIBRARY_PREFIX%\include\jsonarango\arangoquery.h (exit 0) else (exit 1)  # [win]

about:
  home: https://bitbucket.org/gems4/jsonarango
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: A lightweight ArangoDB client C++ library, providing CRUD and query operations
  doc_url: https://bitbucket.org/gems4/jsonarango
  dev_url: https://bitbucket.org/gems4/jsonarango

extra:
  recipe-maintainers:
    - gdmiron
    - sdmytrievs
